### ISSUE TITLE
Arena Ticket Quest

### ISSUE THREAD

**Issue by Actionshd** [ayserjamshidi/DarkBetrayal#42] opened 2018-01-09 01:43 UTC
Accepting Arena Ticket Quest from Crucible Coliseum and completing it makes you acquire a bunch of other quests.
![aion0001](https://user-images.githubusercontent.com/35017185/34701139-24e8e26c-f4ac-11e7-8fc3-922b308e5fe6.jpg)

**Comment by AyserJamshidi** [comment] 2018-01-09 20:06
Those quests activate upon hitting level 65.  I will change their activators later.

Duplicate of #13

**Closed as completed by AyserJamshidi** 2018-01-09 20:06 UTC
